# Generated by Django 5.1.7 on 2025-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='query',
            field=models.TextField(blank=True, help_text='The query that was sent', null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='response',
            field=models.TextField(blank=True, help_text='The response that was received', null=True),
        ),
    ]
