# Generated by Django 5.1.7 on 2025-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_logmessage_query_logmessage_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='user_id',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.TextField(help_text='The log message'),
        ),
    ]
