# Generated by Django 5.1.7 on 2025-11-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_project_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to send notifications to', max_length=254)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable email notifications')),
                ('notify_on_error', models.BooleanField(default=True, help_text='Send email when error logs are received')),
                ('notify_on_warning', models.BooleanField(default=False, help_text='Send email when warning logs are received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Notification Preference',
                'verbose_name_plural': 'Email Notification Preferences',
            },
        ),
    ]
