# Generated by Django 5.1.7 on 2025-03-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_logmessage_user_id_alter_logmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='The user id of the user who made the request', max_length=100)),
                ('message', models.TextField(help_text='The log message')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_log_messages', to='logger.apikey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LlmLogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='The user id of the user who made the request', max_length=100)),
                ('source', models.TextField(help_text='The which model or service the log message is from')),
                ('query', models.TextField(blank=True, help_text='The query that was sent', null=True)),
                ('response', models.TextField(blank=True, help_text='The response that was received', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_log_messages', to='logger.apikey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
