# Generated by Django 5.1.7 on 2025-03-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_eventlogmessage_llmlogmessage_delete_logmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogmessage',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_log_messages', to='logger.apikey'),
        ),
        migrations.AlterField(
            model_name='llmlogmessage',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_log_messages', to='logger.apikey'),
        ),
    ]
